"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


#modole user 


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jmn_ekc_%z^+9$6iw4*+63@pkk_%%_+9ou$v#2#+ef609iofux'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "10.2.5.204", "*"]

# Autoriser les requêtes CORS depuis le frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # URL de développement de Vite REACT
]

# Custom User Model
AUTH_USER_MODEL = 'fajma.Utilisateur'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',
    'fajma',
    'iot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'debug_semoka',
        'USER': 'postgres',
        'PASSWORD': 'Enus814',
        'HOST': 'localhost',
        'PORT': '5432',
    }
    
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# JWT settings
SIMPLE_JWT = {
    'USER_ID_FIELD': 'user_id',  # Utiliser 'user_id' comme champ d'identifiant
    'USER_ID_CLAIM': 'user_id',  # Nom du champ dans le payload du JWT
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Durée de vie du token d'accès
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Durée de vie du refresh token
    'ROTATE_REFRESH_TOKENS': True,  # Générer un nouveau refresh token à chaque rafraîchissement
    'BLACKLIST_AFTER_ROTATION': True,  # Ajouter les anciens refresh tokens à la blacklist
    'AUTH_HEADER_TYPES': ('Bearer',),  # Type d'en-tête attendu
    'SIGNING_KEY': 'votre-cle-secrete-jwt-changez-la',  # Clé pour signer les tokens
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.fenku-it.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'efajma.contact@fenku-it.com'  # Votre App Mail
EMAIL_HOST_PASSWORD = 'cM6-bjYZEwKgxBW'  # Votre mot de passe d'application Mail

# Configuration Django Channels
ASGI_APPLICATION = 'core.asgi.application'

# Configuration des channels (WebSocket) - Utilisation en mémoire pour éviter Redis
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Configuration Redis (commentée temporairement)
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }

# Configuration WebSocket
WEBSOCKET_URL = '/ws/'
WEBSOCKET_HEARTBEAT_INTERVAL = 30  # secondes
WEBSOCKET_TIMEOUT = 300  # 5 minutes


# Configuration CORS pour développement
CORS_ALLOW_ALL_ORIGINS = True

# Configuration WebSocket
WEBSOCKET_ACCEPT_ALL = True

# Configuration du cache Redis pour les données IoT
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# ================================
# Configuration MQTT IoT
# ================================

# Chargement des variables d'environnement MQTT
MQTT_BROKER_HOST = os.getenv('MQTT_BROKER_HOST', 'broker.hivemq.com')
MQTT_BROKER_PORT = int(os.getenv('MQTT_BROKER_PORT', 8883))
MQTT_USERNAME = os.getenv('MQTT_USERNAME', 'FenkuIT_Brocker')
MQTT_PASSWORD = os.getenv('MQTT_PASSWORD', 'FenkuIT@2024')
MQTT_USE_TLS = os.getenv('MQTT_USE_TLS', 'True').lower() == 'true'

# Configuration automatique selon l'environnement
if MQTT_USERNAME and MQTT_PASSWORD:
    # Mode production avec authentification
    MQTT_USE_TLS = True
    if MQTT_BROKER_PORT == 1883:  # Passer au port sécurisé
        MQTT_BROKER_PORT = 8883
else:
    # Mode développement avec broker public
    MQTT_BROKER_HOST = 'broker.hivemq.com'
    MQTT_BROKER_PORT = 1883
    MQTT_USE_TLS = False

# Topics MQTT (avec variables d'environnement)
MQTT_TOPIC_SENSORS = os.getenv('MQTT_TOPIC_SENSORS', 'fenkuit/sensors')
MQTT_TOPIC_COMMANDS = os.getenv('MQTT_TOPIC_COMMANDS', 'fenkuit/devices')
MQTT_TOPIC_STATUS = os.getenv('MQTT_TOPIC_STATUS', 'fenkuit/devices')

MQTT_TOPICS = {
    'SENSOR_DATA': f'{MQTT_TOPIC_SENSORS}/+/data',
    'DEVICE_STATUS': f'{MQTT_TOPIC_SENSORS}/+/status',
    'DEVICE_CONFIG': f'{MQTT_TOPIC_SENSORS}/+/config',
    'COMMANDS': f'{MQTT_TOPIC_COMMANDS}/+/control'
}

# Configuration du client MQTT (avec variables d'environnement)
MQTT_CLIENT_ID = os.getenv('MQTT_CLIENT_ID', 'django_fajma_client')
MQTT_KEEPALIVE = int(os.getenv('MQTT_KEEPALIVE', 60))  # secondes
MQTT_QOS = int(os.getenv('MQTT_QOS', 1))  # Quality of Service (0, 1, ou 2)
MQTT_RETAIN = False  # Messages retained

# Paramètres de reconnexion
MQTT_RECONNECT_DELAY = int(os.getenv('MQTT_RECONNECT_DELAY', 5))
MQTT_MAX_RECONNECT_ATTEMPTS = int(os.getenv('MQTT_MAX_RECONNECT_ATTEMPTS', 10))

# Auto-démarrage du client MQTT
MQTT_AUTO_START = True

# Logging MQTT
MQTT_LOG_LEVEL = 'INFO'  # DEBUG, INFO, WARNING, ERROR