<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> fc99c8a (debut conception dashboard patient)
# Generated by Django 4.2.7 on 2025-05-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': True},
        ),
    ]
<<<<<<< HEAD
=======
# Generated by Django 4.2.7 on 2025-05-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': True},
        ),
    ]
>>>>>>> f575271 (Initial commit: FAJMA IoT Healthcare System with ESP32 integration)
=======
>>>>>>> fc99c8a (debut conception dashboard patient)
