# Generated by Django 4.2.7 on 2025-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0002_alter_utilisateur_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitudesVie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tabagisme', models.CharField(blank=True, max_length=50)),
                ('alcool', models.CharField(blank=True, max_length=50)),
                ('activite_physique', models.CharField(blank=True, max_length=100)),
                ('alimentation', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'habitudes_vie',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': False},
        ),
    ]
