# Generated by Django 4.2.7 on 2025-05-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0003_habitudesvie_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': True},
        ),
    ]