<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> fc99c8a (debut conception dashboard patient)
# Generated by Django 4.2.7 on 2025-06-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0005_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteuriot',
            options={'managed': True},
        ),
    ]
<<<<<<< HEAD
=======
# Generated by Django 4.2.7 on 2025-06-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0005_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteuriot',
            options={'managed': True},
        ),
    ]
>>>>>>> f575271 (Initial commit: FAJMA IoT Healthcare System with ESP32 integration)
=======
>>>>>>> fc99c8a (debut conception dashboard patient)
