# Generated by Django 4.2.7 on 2025-06-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0005_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteuriot',
            options={'managed': True},
        ),
    ]
