<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> fc99c8a (debut conception dashboard patient)
# Generated by Django 4.2.7 on 2025-06-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0006_alter_capteuriot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteuriot',
            options={'managed': False},
        ),
    ]
<<<<<<< HEAD
=======
# Generated by Django 4.2.7 on 2025-06-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0006_alter_capteuriot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteuriot',
            options={'managed': False},
        ),
    ]
>>>>>>> f575271 (Initial commit: FAJMA IoT Healthcare System with ESP32 integration)
=======
>>>>>>> fc99c8a (debut conception dashboard patient)
