# Generated by Django 4.2.7 on 2025-06-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0006_alter_capteuriot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteuriot',
            options={'managed': False},
        ),
    ]
