# Generated by Django 4.2.7 on 2025-06-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0007_alter_capteuriot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteuriot',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'managed': True},
        ),
    ]