# Generated by Django 4.2.7 on 2025-06-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0008_alter_capteuriot_options_alter_consultation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capteuriot',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'managed': False},
        ),
    ]
