<<<<<<< HEAD
# Generated by Django 4.2.7 on 2025-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0009_alter_capteuriot_options_alter_consultation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('allergie_id', models.AutoField(primary_key=True, serialize=False)),
                ('substance', models.CharField(max_length=100)),
                ('severite', models.CharField(max_length=20)),
                ('date_identification', models.DateField()),
            ],
            options={
                'db_table': 'allergies',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='biometrie',
            table='biometrie',
        ),
    ]
=======
# Generated by Django 4.2.7 on 2025-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0009_alter_capteuriot_options_alter_consultation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('allergie_id', models.AutoField(primary_key=True, serialize=False)),
                ('substance', models.CharField(max_length=100)),
                ('severite', models.CharField(max_length=20)),
                ('date_identification', models.DateField()),
            ],
            options={
                'db_table': 'allergies',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='biometrie',
            table='biometrie',
        ),
    ]
>>>>>>> f575271 (Initial commit: FAJMA IoT Healthcare System with ESP32 integration)
