# Generated by Django 4.2.7 on 2025-06-13 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0010_allergie_alter_biometrie_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': True},
        ),
    ]
