<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> fc99c8a (debut conception dashboard patient)
# Generated by Django 4.2.7 on 2025-06-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0012_remove_utilisateur_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': False},
        ),
    ]
<<<<<<< HEAD
=======
# Generated by Django 4.2.7 on 2025-06-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0012_remove_utilisateur_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': False},
        ),
    ]
>>>>>>> f575271 (Initial commit: FAJMA IoT Healthcare System with ESP32 integration)
=======
>>>>>>> fc99c8a (debut conception dashboard patient)
