# Generated by Django 4.2.7 on 2025-06-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0012_remove_utilisateur_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'managed': False},
        ),
    ]