# Generated by Django 4.2.7 on 2025-08-29 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0013_alter_utilisateur_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertesIoT',
            fields=[
                ('alerte_id', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique'), ('emergency', 'Urgence')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('resolue', 'Résolue'), ('ignoree', 'Ignorée')], default='active', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alertes_iot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DispositivesIoT',
            fields=[
                ('dispositif_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type_dispositif', models.CharField(choices=[('esp32', 'ESP32'), ('arduino', 'Arduino'), ('raspberry_pi', 'Raspberry Pi'), ('autre', 'Autre')], max_length=50)),
                ('adresse_mac', models.CharField(max_length=17, unique=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_panne', 'En panne'), ('maintenance', 'En maintenance')], default='actif', max_length=20)),
                ('date_installation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('version_firmware', models.CharField(blank=True, max_length=50, null=True)),
                ('localisation', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'dispositives_iot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonneesCapteursIoT',
            fields=[
                ('donnee_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_capteur', models.CharField(choices=[('temperature', 'Température'), ('humidite', 'Humidité'), ('pression_arterielle', 'Pression artérielle'), ('frequence_cardiaque', 'Fréquence cardiaque'), ('oxygene_sang', 'Oxygène dans le sang'), ('glucose', 'Glucose'), ('poids', 'Poids'), ('mouvement', 'Mouvement'), ('autre', 'Autre')], max_length=50)),
                ('valeur', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unite', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('qualite_signal', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'donnees_capteurs_iot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionsWebSocket',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=200)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('fermee', 'Fermée'), ('expiree', 'Expirée')], default='active', max_length=20)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions_websocket',
                'managed': False,
            },
        ),
    ]
