# Generated by Django 4.2.7 on 2025-09-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fajma', '0013_alter_utilisateur_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapteurIoT',
        ),
    ]
